[Writable]
LogLevel = "INFO"
  # Example InsecureSecrets configuration that simulates SecretStore for when EDGEX_SECURITY_SECRET_STORE=false
  # InsecureSecrets are required for when Redis is used for message bus
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""

[Service]
BootTimeout = 30000
HealthCheckInterval = "10s"
Host = "localhost"
ServerBindAddr = ""  # blank value defaults to Service.Host value
Port = 59100
Protocol = "http"
StartupMsg = "device SAK started"
RequestTimeout = "5s"
ConnectRetries = 10
Labels = []
EnableAsyncReadings = false
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"


[Clients]
  [Clients.core-data]
  Protocol = "http"
  Host = "localhost"
  Port = 59880

  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

[Device]
  DataTransform = true
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  ProfilesDir = "./res/profiles"
  DevicesDir = "./res/devices"
  UpdateLastConnected = false
  AsyncBufferSize = 1
  EnableAsyncReadings = true
  Labels = []
  [Device.Discovery]
    Enabled = false
    Interval = "30s"

