[[DeviceList]]
  Name = "SAK"
  ProfileName = "SAK"
  Description = "Example of SAK Device"
  Labels = [ "device-sak" ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = "device-SAK"

